kind: Service
apiVersion: v1
metadata:
  name: react-portifolio
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 32000
  selector:
    app: react-portifolio
